/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista clientes de forma paginada
         * @description Retorna uma página de clientes, com filtros opcionais por nome e CNPJ.
         */
        get: operations["ListarClientes"];
        put?: never;
        /** Cria um novo cliente */
        post: operations["CriarCliente"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta cliente por Id */
        get: operations["ConsultarCliente"];
        /** Atualiza um cliente existente */
        put: operations["AtualizarCliente"];
        post?: never;
        /** Exclui (logicamente) um cliente */
        delete: operations["ExcluirCliente"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grupos-economicos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista grupos econômicos de forma paginada */
        get: operations["ListarGruposEconomicos"];
        put?: never;
        /** Cria um novo grupo econômico */
        post: operations["CriarGrupoEconomico"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grupos-economicos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta grupo econômico por Id */
        get: operations["ConsultarGrupoEconomico"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contratos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista contratos de forma paginada, filtrável e ordenável
         * @description Cobre os mesmos filtros da tela de Listagem de Contratos do frontend (busca, segmento, tipo, situação da PCR, denúncia, bandeira, UF, hierarquia comercial).
         */
        get: operations["ListarContratos"];
        put?: never;
        /** Cria um novo contrato */
        post: operations["CriarContrato"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contratos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta contrato por Id */
        get: operations["ConsultarContrato"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contratos/{id}/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra um evento no ciclo de vida do contrato (Renovação, Readequação, Cessão, Sucessão, Denúncia ou Encerramento) */
        post: operations["RegistrarEventoContrato"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AtualizarClienteBody: {
            nome: string;
            cnpj: string;
            endereco: string;
            ativo: boolean;
        };
        AtualizarClienteResponse: {
            /** Format: int32 */
            id: number;
            nome: string;
            cnpj: string;
            endereco: string;
            ativo: boolean;
            /** Format: date-time */
            dataAlteracao: string | null;
        };
        ConsultarClienteResponse: {
            /** Format: int32 */
            id: number;
            nome: string;
            cnpj: string;
            endereco: string;
            ativo: boolean;
            /** Format: date-time */
            dataCriacao: string;
            /** Format: date-time */
            dataAlteracao: string | null;
        };
        ConsultarContratoResponse: {
            /** Format: int32 */
            id: number;
            contratoId: string;
            /** Format: int32 */
            clienteId: number;
            clienteNome: string;
            clienteCnpj: string;
            clienteNrSap: string | null;
            clienteUf: string | null;
            /** Format: int32 */
            grupoEconomicoId: number | null;
            grupoEconomicoNome: string | null;
            pcr: string;
            segmento: components["schemas"]["Segmento"];
            tipo: components["schemas"]["TipoContrato"];
            situacaoMes: components["schemas"]["SituacaoMes"];
            bandeira: string;
            registradoAle: boolean;
            /** Format: date */
            dataRegistroAnp: string | null;
            /** Format: date */
            inicioVigencia: string;
            /** Format: date */
            fimVigencia: string;
            /** Format: double */
            volumeMensalContratado: number;
            /** Format: double */
            galonagemContratada: number;
            /** Format: double */
            galonagemFaturada: number;
            /** Format: double */
            galonagemSaldo: number;
            /** Format: double */
            galonagemPercentual: number;
            situacaoPcr: components["schemas"]["SituacaoPcr"];
            /** Format: double */
            margemBase: number;
            /** Format: double */
            tirContratada: number | null;
            greenfield: boolean;
            denuncia: boolean;
            garantia: boolean;
            sublocado: boolean;
            encerrado: boolean;
            papelGuardaChuva: components["schemas"]["NullableOfPapelGuardaChuva"];
            codigoGuardaChuva: string | null;
            diretoria: string;
            regionalVendas: string;
            pontoVenda: string;
            consultor: string;
            observacao: string | null;
            clausula: string | null;
            cnpjSucedido: string | null;
            razaoSucedido: string | null;
            /** Format: date-time */
            dataCriacao: string;
            /** Format: date-time */
            dataAlteracao: string | null;
            eventos: components["schemas"]["EventoContratoItem"][];
        };
        ConsultarGrupoEconomicoResponse: {
            /** Format: int32 */
            id: number;
            codigo: string;
            nome: string;
            /** Format: date-time */
            dataCriacao: string;
            /** Format: date-time */
            dataAlteracao: string | null;
        };
        CriarClienteRequest: {
            nome: string;
            cnpj: string;
            endereco: string;
        };
        CriarClienteResponse: {
            /** Format: int32 */
            id: number;
            nome: string;
            cnpj: string;
            endereco: string;
            ativo: boolean;
            /** Format: date-time */
            dataCriacao: string;
        };
        CriarContratoRequest: {
            /** Format: int32 */
            clienteId: number;
            pcr: string;
            segmento: components["schemas"]["Segmento"];
            tipo: components["schemas"]["TipoContrato"];
            situacaoMes: components["schemas"]["SituacaoMes"];
            bandeira: string;
            registradoAle: boolean;
            /** Format: date */
            inicioVigencia: string;
            /** Format: date */
            fimVigencia: string;
            /** Format: double */
            volumeMensalContratado: number;
            /** Format: double */
            margemBase: number;
            diretoria: string;
            regionalVendas: string;
            pontoVenda: string;
            consultor: string;
            /** @default false */
            greenfield: boolean;
        };
        CriarContratoResponse: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            clienteId: number;
            pcr: string;
            segmento: components["schemas"]["Segmento"];
            tipo: components["schemas"]["TipoContrato"];
            /** Format: date */
            inicioVigencia: string;
            /** Format: date */
            fimVigencia: string;
            /** Format: date-time */
            dataCriacao: string;
        };
        CriarGrupoEconomicoRequest: {
            codigo: string;
            nome: string;
        };
        CriarGrupoEconomicoResponse: {
            /** Format: int32 */
            id: number;
            codigo: string;
            nome: string;
            /** Format: date-time */
            dataCriacao: string;
        };
        EventoContratoItem: {
            /** Format: int32 */
            id: number;
            tipo: components["schemas"]["TipoEventoContrato"];
            /** Format: date */
            data: string;
            descricao: string;
        };
        HttpValidationProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
            errors?: {
                [key: string]: string[];
            };
        };
        ListarClientesResponse: {
            /** Format: int32 */
            id: number;
            nome: string;
            cnpj: string;
            endereco: string;
            ativo: boolean;
            /** Format: date-time */
            dataCriacao: string;
        };
        ListarContratosResponse: {
            /** Format: int32 */
            id: number;
            contratoId: string;
            pcr: string;
            clienteNome: string;
            clienteCnpj: string;
            clienteNrSap: string | null;
            clienteUf: string | null;
            grupoEconomicoNome: string | null;
            segmento: components["schemas"]["Segmento"];
            tipo: components["schemas"]["TipoContrato"];
            /** Format: double */
            galonagemContratada: number;
            /** Format: double */
            galonagemFaturada: number;
            /** Format: double */
            galonagemPercentual: number;
            situacaoPcr: components["schemas"]["SituacaoPcr"];
            /** Format: date */
            fimVigencia: string;
            denuncia: boolean;
            bandeira: string;
            diretoria: string;
            regionalVendas: string;
            pontoVenda: string;
            consultor: string;
            papelGuardaChuva: components["schemas"]["NullableOfPapelGuardaChuva"];
        };
        ListarGruposEconomicosResponse: {
            /** Format: int32 */
            id: number;
            codigo: string;
            nome: string;
        };
        /** @enum {unknown|null} */
        NullableOfPapelGuardaChuva: "Principal" | "Adicional" | null;
        PaginationResponseOfListarClientesResponse: {
            items: components["schemas"]["ListarClientesResponse"][];
            /** Format: int32 */
            pageIndex: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages?: number;
        };
        PaginationResponseOfListarContratosResponse: {
            items: components["schemas"]["ListarContratosResponse"][];
            /** Format: int32 */
            pageIndex: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages?: number;
        };
        PaginationResponseOfListarGruposEconomicosResponse: {
            items: components["schemas"]["ListarGruposEconomicosResponse"][];
            /** Format: int32 */
            pageIndex: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        };
        RegistrarEventoContratoBody: {
            tipo: components["schemas"]["TipoEventoContrato"];
            /** Format: date */
            data: string;
            descricao: string;
        };
        RegistrarEventoContratoResponse: {
            /** Format: int32 */
            contratoId: number;
            tipo: components["schemas"]["TipoEventoContrato"];
            /** Format: date */
            data: string;
            descricao: string;
            contratoEncerrado: boolean;
            contratoEmDenuncia: boolean;
        };
        /** @enum {unknown} */
        Segmento: "Rede" | "Grr" | "Cofa" | "Cofd" | "Cofar" | "Outros" | "Spot";
        /** @enum {unknown} */
        SituacaoMes: "Ativo" | "Inativo";
        /** @enum {unknown} */
        SituacaoPcr: "Vigente" | "VencidoPorGalonagem" | "VencidoPorData";
        /** @enum {unknown} */
        TipoContrato: "Pcvm" | "Imagem" | "Comodato";
        /** @enum {unknown} */
        TipoEventoContrato: "NovoNegocio" | "Renovacao" | "Readequacao" | "Cessao" | "Sucessao" | "Denuncia" | "Encerramento";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListarClientes: {
        parameters: {
            query?: {
                FiltroNome?: string;
                FiltroCnpj?: string;
                SortBy?: string;
                SortDirection?: string;
                PageIndex?: number;
                PageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationResponseOfListarClientesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CriarCliente: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarClienteRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriarClienteResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ConsultarCliente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultarClienteResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AtualizarCliente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarClienteBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtualizarClienteResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ExcluirCliente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListarGruposEconomicos: {
        parameters: {
            query?: {
                FiltroNome?: string;
                SortBy?: string;
                SortDirection?: string;
                PageIndex?: number;
                PageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationResponseOfListarGruposEconomicosResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CriarGrupoEconomico: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarGrupoEconomicoRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriarGrupoEconomicoResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ConsultarGrupoEconomico: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultarGrupoEconomicoResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListarContratos: {
        parameters: {
            query?: {
                Busca?: string;
                Segmentos?: components["schemas"]["Segmento"][];
                Tipos?: components["schemas"]["TipoContrato"][];
                SituacoesPcr?: components["schemas"]["SituacaoPcr"][];
                EmDenuncia?: boolean;
                Bandeira?: string;
                Ufs?: string[];
                Diretoria?: string;
                RegionalVendas?: string;
                PontoVenda?: string;
                Consultor?: string;
                SortBy?: string;
                SortDirection?: string;
                PageIndex?: number;
                PageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationResponseOfListarContratosResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CriarContrato: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarContratoRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriarContratoResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ConsultarContrato: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultarContratoResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RegistrarEventoContrato: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarEventoContratoBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrarEventoContratoResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
