// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalAle.Data.SqlServer;

#nullable disable

namespace PortalAle.Data.SqlServer.Persistencia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260729001239_CriarTabelaCliente")]
    partial class CriarTabelaCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalAle.Domain.Clientes.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCliente")
                        .HasComment("Identificador único do cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("InAtivo")
                        .HasComment("Indicador se o cliente está ativo (default: 1)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("NrCnpj")
                        .HasComment("CNPJ do cliente (somente dígitos)");

                    b.Property<DateTimeOffset?>("DataAlteracao")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DhAlteracao")
                        .HasComment("Data e hora da última alteração do registro");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DhInclusao")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()")
                        .HasComment("Data e hora de criação do registro");

                    b.Property<DateTimeOffset?>("DataExclusao")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DhExclusao")
                        .HasComment("Data e hora da exclusão lógica do registro (soft delete)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DsEndereco")
                        .HasComment("Endereço do cliente");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NmRazaoSocial")
                        .HasComment("Razão social do cliente");

                    b.HasKey("Id")
                        .HasName("PK_Cliente");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("UQ_Cliente_NrCnpj");

                    b.ToTable("Cliente", "dbo", t =>
                        {
                            t.HasComment("Cadastro de clientes (pessoa jurídica)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
