// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalAle.Data.SqlServer;

#nullable disable

namespace PortalAle.Data.SqlServer.Persistencia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260805215827_CriarTabelaContrato")]
    partial class CriarTabelaContrato
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalAle.Domain.Clientes.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCliente")
                        .HasComment("Identificador único do cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("InAtivo")
                        .HasComment("Indicador se o cliente está ativo (default: 1)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("NrCnpj")
                        .HasComment("CNPJ do cliente (somente dígitos)");

                    b.Property<DateTimeOffset?>("DataAlteracao")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DhAlteracao")
                        .HasComment("Data e hora da última alteração do registro");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DhInclusao")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()")
                        .HasComment("Data e hora de criação do registro");

                    b.Property<DateTimeOffset?>("DataExclusao")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DhExclusao")
                        .HasComment("Data e hora da exclusão lógica do registro (soft delete)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DsEndereco")
                        .HasComment("Endereço do cliente");

                    b.Property<int?>("GrupoEconomicoId")
                        .HasColumnType("int")
                        .HasColumnName("IdGrupoEconomico")
                        .HasComment("Grupo econômico ao qual o cliente pertence (opcional)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NmRazaoSocial")
                        .HasComment("Razão social do cliente");

                    b.Property<string>("NrSap")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("NrSap")
                        .HasComment("Número SAP do cliente (10 dígitos) — identifica o cliente (contexto seção 9)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("SgUf")
                        .HasComment("UF do CNPJ/ponto de venda");

                    b.HasKey("Id")
                        .HasName("PK_Cliente");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("UQ_Cliente_NrCnpj");

                    b.HasIndex("GrupoEconomicoId")
                        .HasDatabaseName("IX_Cliente_IdGrupoEconomico");

                    b.ToTable("Cliente", "dbo", t =>
                        {
                            t.HasComment("Cadastro de clientes (pessoa jurídica)");
                        });
                });

            modelBuilder.Entity("PortalAle.Domain.Contratos.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdContrato")
                        .HasComment("Identificador único do contrato");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("DsBandeira")
                        .HasComment("Bandeira ANP — atualização hoje manual, mecanismo automático é item em aberto");

                    b.Property<string>("Clausula")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TxClausula")
                        .HasComment("Cláusulas específicas do contrato");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("IdCliente")
                        .HasComment("Cliente (CNPJ) titular do contrato");

                    b.Property<string>("CnpjSucedido")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("NrCnpjSucedido")
                        .HasComment("CNPJ do contrato/cliente predecessor, em caso de Sucessão");

                    b.Property<string>("CodigoGuardaChuva")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CdGuardaChuva")
                        .HasComment("Código de agrupamento do guarda-chuva");

                    b.Property<string>("Consultor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NmConsultor")
                        .HasComment("Consultor comercial responsável");

                    b.Property<DateTimeOffset?>("DataAlteracao")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DhAlteracao")
                        .HasComment("Data e hora da última alteração do registro");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DhInclusao")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()")
                        .HasComment("Data e hora de criação do registro");

                    b.Property<DateOnly?>("DataRegistroAnp")
                        .HasColumnType("date")
                        .HasColumnName("DtRegistroAnp")
                        .HasComment("Data do último registro/atualização junto à ANP");

                    b.Property<bool>("Denuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("InDenuncia")
                        .HasComment("Indicador de contrato em denúncia");

                    b.Property<string>("Diretoria")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("DsDiretoria")
                        .HasComment("Diretoria comercial — snapshot textual, origem (SAP vs. manual) é decisão em aberto");

                    b.Property<bool>("Encerrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("InEncerrado")
                        .HasComment("Indicador de contrato encerrado (mutado via Contrato.RegistrarEvento com TipoEventoContrato.Encerramento)");

                    b.Property<DateOnly>("FimVigencia")
                        .HasColumnType("date")
                        .HasColumnName("DtFimVigencia")
                        .HasComment("Data de fim da vigência contratual");

                    b.Property<decimal>("GalonagemFaturada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("MdGalonagemFaturada")
                        .HasComment("Galonagem faturada acumulada — atualizada pela integração SAP/PCR (Fase 5); 0 até lá");

                    b.Property<bool>("Garantia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("InGarantia")
                        .HasComment("Indicador de garantia contratual");

                    b.Property<bool>("Greenfield")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("InGreenfield")
                        .HasComment("Indicador de posto Greenfield (novo, em curva de maturação)");

                    b.Property<DateOnly>("InicioVigencia")
                        .HasColumnType("date")
                        .HasColumnName("DtInicioVigencia")
                        .HasComment("Data de início da vigência contratual");

                    b.Property<decimal>("MargemBase")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PrMargemBase")
                        .HasComment("Taxa de margem base do contrato");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TxObservacao")
                        .HasComment("Observações livres sobre o contrato");

                    b.Property<string>("PapelGuardaChuva")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("DsPapelGuardaChuva")
                        .HasComment("Papel no guarda-chuva (Principal/Adicional) — versão embutida enquanto GuardaChuva completo (Fase 1.2) está bloqueado");

                    b.Property<string>("Pcr")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NrPcr")
                        .HasComment("Número da PCR/PCF (sem prefixo — prefixo PCR/PCF é derivado do Segmento na apresentação)");

                    b.Property<string>("PontoVenda")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("DsPontoVenda")
                        .HasComment("Ponto de venda/revenda (RN) — snapshot textual");

                    b.Property<string>("RazaoSucedido")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NmRazaoSucedido")
                        .HasComment("Razão social do predecessor, em caso de Sucessão");

                    b.Property<string>("RegionalVendas")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("DsRegionalVendas")
                        .HasComment("Regional de vendas (GR) — snapshot textual");

                    b.Property<bool>("RegistradoAle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("InRegistradoAle")
                        .HasComment("Indicador se o posto está registrado como bandeira ALE junto à ANP");

                    b.Property<string>("Segmento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DsSegmento")
                        .HasComment("Segmento do contrato (Rede/Grr/Cofa/Cofd/Cofar/Outros/Spot)");

                    b.Property<string>("SituacaoMes")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("DsSituacaoMes")
                        .HasComment("Situação do contrato no mês (Ativo/Inativo), vinda do SICOF/PCR");

                    b.Property<bool>("Sublocado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("InSublocado")
                        .HasComment("Indicador de imóvel sublocado de terceiro");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DsTipoContrato")
                        .HasComment("Tipo do contrato (Pcvm/Imagem/Comodato)");

                    b.Property<decimal?>("TirContratada")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PrTirContratada")
                        .HasComment("TIR Contratada — fixa na aprovação (única das 3 TIRs persistida aqui, ver seção 10 do contexto)");

                    b.Property<decimal>("VolumeMensalContratado")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("MdVolumeMensalContratado")
                        .HasComment("Volume mensal contratado (m³) — base para o cálculo de galonagem contratada");

                    b.HasKey("Id")
                        .HasName("PK_Contrato");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_Contrato_IdCliente");

                    b.HasIndex("FimVigencia")
                        .HasDatabaseName("IX_Contrato_DtFimVigencia");

                    b.HasIndex("Pcr")
                        .IsUnique()
                        .HasDatabaseName("UQ_Contrato_NrPcr");

                    b.HasIndex("Segmento")
                        .HasDatabaseName("IX_Contrato_DsSegmento");

                    b.ToTable("Contrato", "dbo", t =>
                        {
                            t.HasComment("Base contratual consolidada (Rede/GRR/B2B)");
                        });
                });

            modelBuilder.Entity("PortalAle.Domain.Contratos.EventoContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdHistoricoEventoContrato")
                        .HasComment("Identificador único do evento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoId")
                        .HasColumnType("int")
                        .HasColumnName("IdContrato")
                        .HasComment("Contrato ao qual o evento pertence");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("DtEvento")
                        .HasComment("Data em que o evento ocorreu");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TxDescricao")
                        .HasComment("Descrição do evento");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DsTipoEvento")
                        .HasComment("Tipo do evento (NovoNegocio/Renovacao/Readequacao/Cessao/Sucessao/Denuncia/Encerramento)");

                    b.HasKey("Id")
                        .HasName("PK_HistoricoEventoContrato");

                    b.HasIndex("ContratoId")
                        .HasDatabaseName("IX_HistoricoEventoContrato_IdContrato");

                    b.ToTable("HistoricoEventoContrato", "dbo", t =>
                        {
                            t.HasComment("Histórico de eventos do ciclo de vida do contrato");
                        });
                });

            modelBuilder.Entity("PortalAle.Domain.GruposEconomicos.GrupoEconomico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdGrupoEconomico")
                        .HasComment("Identificador único do grupo econômico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CdSap")
                        .HasComment("Código SAP do grupo econômico (3 dígitos)");

                    b.Property<DateTimeOffset?>("DataAlteracao")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DhAlteracao")
                        .HasComment("Data e hora da última alteração do registro");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DhInclusao")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()")
                        .HasComment("Data e hora de criação do registro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NmGrupo")
                        .HasComment("Nome do grupo econômico");

                    b.HasKey("Id")
                        .HasName("PK_GrupoEconomico");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UQ_GrupoEconomico_CdSap");

                    b.ToTable("GrupoEconomico", "dbo", t =>
                        {
                            t.HasComment("Grupo econômico — conjunto de CNPJs do mesmo grupo controlador (cadastro manual, placeholder até integração SAP)");
                        });
                });

            modelBuilder.Entity("PortalAle.Domain.Clientes.Cliente", b =>
                {
                    b.HasOne("PortalAle.Domain.GruposEconomicos.GrupoEconomico", "GrupoEconomico")
                        .WithMany()
                        .HasForeignKey("GrupoEconomicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Cliente_GrupoEconomico");

                    b.Navigation("GrupoEconomico");
                });

            modelBuilder.Entity("PortalAle.Domain.Contratos.Contrato", b =>
                {
                    b.HasOne("PortalAle.Domain.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Contrato_Cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PortalAle.Domain.Contratos.EventoContrato", b =>
                {
                    b.HasOne("PortalAle.Domain.Contratos.Contrato", "Contrato")
                        .WithMany("Eventos")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HistoricoEventoContrato_Contrato");

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("PortalAle.Domain.Contratos.Contrato", b =>
                {
                    b.Navigation("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
